# Generated by Django 4.2.28 on 2026-09-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyexpense',
            name='accounting_pending',
            field=models.BooleanField(default=False, help_text="Vrai si l'écriture comptable de la dépense a échoué et doit être rejouée (commande replay_accounting).", verbose_name='Écriture comptable en attente'),
        ),
        migrations.AddField(
            model_name='dailyrecipe',
            name='accounting_pending',
            field=models.BooleanField(default=False, help_text="Vrai si l'écriture comptable de la recette a échoué et doit être rejouée (commande replay_accounting).", verbose_name='Écriture comptable en attente'),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='accounting_pending',
            field=models.BooleanField(default=False, help_text="Vrai si l'écriture comptable du paiement a échoué et doit être rejouée (commande replay_accounting).", verbose_name='Écriture comptable en attente'),
        ),
    ]
