# Generated by Django 4.2.28 on 2026-09-22 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dailyexpense_accounting_pending_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('delete_at', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.IntegerField(verbose_name='Quantité commandée')),
                ('estimated_purchase_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Coût d'achat unitaire estimé")),
                ('status', models.CharField(choices=[('ORDERED', 'Commandé'), ('RECEIVED', 'Reçu')], default='ORDERED', max_length=10, verbose_name='Statut')),
                ('daily', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='core.daily', verbose_name='Journée')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='core.product', verbose_name='Produit')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to=settings.AUTH_USER_MODEL, verbose_name='Personnel')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='core.supplier', verbose_name='Fournisseur')),
                ('supply', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_order', to='core.supply', verbose_name='Approvisionnement reçu')),
            ],
            options={
                'verbose_name': 'Commande fournisseur',
                'verbose_name_plural': 'Commandes fournisseurs',
                'db_table': 'purchase_order',
                'ordering': ['-create_at'],
            },
        ),
    ]
