# Generated by Django 4.2.28 on 2026-09-23 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_purchaseorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='min_salable_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prix minimum autorisé pour la vente', max_digits=10, null=True, verbose_name='Prix minimum autorisé pour la vente'),
        ),
    ]
