# Generated by Django 4.2.28 on 2026-09-23 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_min_salable_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Espèces'), ('MOBILE_MONEY', 'Mobile Money'), ('BANK_TRANSFER', 'Virement bancaire'), ('CHECK', 'Chèque')], max_length=20, null=True, verbose_name='Mode de paiement'),
        ),
    ]
