from django.urls import path
from . import views, views_invitations

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('', views.dashboard, name='dashboard'),
    path('dashboard/', views.dashboard, name='dashboard_alias'),
    path('statistics/', views.statistics, name='statistics'),
    path('statistics/products/', views.product_statistics, name='product_statistics'),
    path('statistics/sales/', views.sales_statistics, name='sales_statistics'),
    path('statistics/clients/', views.client_statistics, name='client_statistics'),
    path('statistics/expenses/', views.expense_statistics, name='expense_statistics'),
    path('statistics/supplies/', views.supply_statistics, name='supply_statistics'),
    path('statistics/suppliers/', views.supplier_statistics, name='supplier_statistics'),
    path('statistics/staff/', views.personnel_statistics, name='personnel_statistics'),
    path('sales/', views.sales, name='sales'),
    path('sales/history/', views.sales_history, name='sales_history'),
    path('sales/<int:sale_id>/cancel/', views.cancel_sale, name='cancel_sale'),
    path('sales/<int:sale_id>/partial-return/', views.partial_return_sale, name='partial_return_sale'),
    path('products/', views.products, name='products'),
    path('products/add/', views.add_product, name='add_product'),
    path('products/export/', views.export_products_csv, name='export_products_csv'),
    path('products/import/', views.import_products_csv, name='import_products_csv'),
    path('products/references/', views.product_references, name='product_references'),
    path('products/references/<slug:kind>/add/', views.add_reference, name='add_reference'),
    path('products/references/<slug:kind>/<int:pk>/edit/', views.edit_reference, name='edit_reference'),
    path('products/references/<slug:kind>/<int:pk>/delete/', views.delete_reference, name='delete_reference'),
    path('products/<int:pk>/', views.product_detail, name='product_detail'),
    path('products/<int:pk>/edit/', views.edit_product, name='edit_product'),
    path('products/<int:pk>/delete/', views.delete_product, name='delete_product'),
    path('inventory/', views.inventory, name='inventory'),
    path('inventory/add/', views.add_inventory, name='add_inventory'),
    path('inventory/history/', views.inventory_history, name='inventory_history'),
    path('inventory/close/', views.close_inventory_summary, name='close_inventory_summary'),
    path('inventory/close/confirm/', views.close_inventory_confirm, name='close_inventory_confirm'),
    path('supplies/', views.supplies, name='supplies'),
    path('supplies/add/', views.add_supply, name='add_supply'),
    path('supplies/<int:supply_id>/cancel/', views.cancel_supply, name='cancel_supply'),
    path('supplies/orders/', views.purchase_orders, name='purchase_orders'),
    path('supplies/orders/add/', views.add_purchase_order, name='add_purchase_order'),
    path('supplies/orders/<int:pk>/receive/', views.receive_purchase_order, name='receive_purchase_order'),
    path('supplies/orders/<int:pk>/cancel/', views.cancel_purchase_order, name='cancel_purchase_order'),
    path('supplies/<int:supply_id>/partial-return/', views.partial_return_supply, name='partial_return_supply'),
    path('contacts/', views.contacts, name='contacts'),
    # Invitations d'employés : mode plateforme uniquement (404 sinon).
    path('contacts/invitations/', views_invitations.invitations, name='invitations'),
    path('contacts/invitations/envoyer/', views_invitations.envoyer_invitation, name='send_invitation'),
    path('contacts/invitations/<int:pk>/renvoyer/', views_invitations.renvoyer_invitation, name='resend_invitation'),
    path('contacts/invitations/<int:pk>/revoquer/', views_invitations.revoquer_invitation, name='revoke_invitation'),
    path('invitation/<str:token>/', views_invitations.accepter_invitation, name='accept_invitation'),
    path('contacts/clients/add/', views.add_client, name='add_client'),
    path('contacts/clients/<int:pk>/edit/', views.edit_client, name='edit_client'),
    path('contacts/clients/<int:pk>/delete/', views.delete_client, name='delete_client'),
    path('contacts/staff/add/', views.add_staff, name='add_staff'),
    path('contacts/staff/<int:pk>/edit/', views.edit_staff, name='edit_staff'),
    path('contacts/staff/<int:pk>/toggle-active/', views.toggle_staff_active, name='toggle_staff_active'),
    path('contacts/staff/<int:pk>/reset-password/', views.reset_staff_password, name='reset_staff_password'),
    path('suppliers/', views.suppliers_list, name='suppliers'),
    path('suppliers/add/', views.add_supplier, name='add_supplier'),
    path('suppliers/<int:pk>/edit/', views.edit_supplier, name='edit_supplier'),
    path('suppliers/<int:pk>/delete/', views.delete_supplier, name='delete_supplier'),
    path('expenses-recipe/', views.expenses, name='expenses'),
    path('expenses/add/', views.add_expense, name='add_expense'),
    path('expenses/add/ajax/', views.add_expense_ajax, name='add_expense_ajax'),
    path('recipes/add/', views.add_recipe, name='add_recipe'),
    path('daily/summary/', views.get_daily_summary, name='get_daily_summary'),
    path('daily/close/', views.close_daily, name='close_daily'),
    path('reports/', views.reports, name='reports'),
    path('settings/', views.settings, name='settings'),
    path('settings/migration/', views.data_migration, name='data_migration'),

    # Comptabilité
    path('accounting/references/', views.accounting_references, name='accounting_references'),
    path('accounting/references/<slug:kind>/add/', views.add_accounting_reference, name='add_accounting_reference'),
    path('accounting/references/<slug:kind>/<int:pk>/edit/', views.edit_accounting_reference, name='edit_accounting_reference'),
    path('accounting/references/<slug:kind>/<int:pk>/delete/', views.delete_accounting_reference, name='delete_accounting_reference'),
    path('accounting/journal/', views.accounting_journal, name='accounting_journal'),
    path('accounting/journal/add/', views.accounting_add_entry, name='accounting_add_entry'),
    path('accounting/ledger/', views.accounting_general_ledger, name='accounting_ledger'),
    path('accounting/balance/', views.accounting_trial_balance, name='accounting_balance'),
    path('accounting/chart/', views.accounting_chart_of_accounts, name='accounting_chart'),
    path('accounting/chart/export/', views.export_chart_of_accounts, name='export_chart_of_accounts'),
    path('accounting/chart/import/', views.import_chart_of_accounts, name='import_chart_of_accounts'),

    # Phase 2 — Trésorerie, Paiements, Factures
    path('accounting/treasury/', views.treasury_dashboard, name='treasury_dashboard'),
    path('accounting/credit-sales/', views.credit_sales_list, name='credit_sales'),
    path('accounting/credit-sales/<int:credit_sale_id>/payment/', views.record_credit_payment, name='record_credit_payment'),
    path('accounting/supplier-payments/', views.supplier_payments_list, name='supplier_payments'),
    path('accounting/supplier-payments/add/', views.add_supplier_payment, name='add_supplier_payment'),
    path('accounting/supply/<int:supply_id>/payment/', views.record_supply_payment, name='record_supply_payment'),
    path('accounting/invoices/', views.invoices_list, name='invoices'),
    path('accounting/invoices/generate/<int:sale_id>/', views.generate_invoice, name='generate_invoice'),
    path('accounting/invoices/<int:pk>/pdf/', views.invoice_pdf, name='invoice_pdf'),

    # Phase 3 — Rapports financiers
    path('accounting/income-statement/', views.income_statement, name='income_statement'),
    path('accounting/balance-sheet/', views.balance_sheet, name='balance_sheet'),
    path('accounting/aged-balance/', views.aged_balance, name='aged_balance'),
    path('accounting/product-margins/', views.product_margins, name='product_margins'),
    path('accounting/export/<str:report_type>/', views.export_report_csv, name='export_report_csv'),

    # Phase 4 — TVA, Rapprochement bancaire, Clôture d'exercice
    path('accounting/vat-declaration/', views.vat_declaration, name='vat_declaration'),
    path('accounting/bank-reconciliation/', views.bank_reconciliation, name='bank_reconciliation'),
    path('accounting/reconcile/', views.reconcile_entry, name='reconcile_entry'),
    path('accounting/unreconcile/', views.unreconcile_entry, name='unreconcile_entry'),
    path('accounting/exercise-closing/', views.exercise_closing_view, name='exercise_closing'),
    path('accounting/exercise-closing/close/', views.close_exercise_action, name='close_exercise_action'),
]
