# Generated by Django 4.2.28 on 2026-09-20 17:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('delete_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text="Libellé utilisé par la plateforme. Le nom imprimé sur les reçus se règle dans les paramètres de l'espace.", max_length=200, verbose_name='Raison sociale')),
                ('slug', models.SlugField(help_text="Identifiant de l'espace : <sous-domaine>.exemple.com", max_length=40, unique=True, verbose_name='Sous-domaine')),
                ('db_name', models.CharField(max_length=64, unique=True, verbose_name='Nom de la base de données')),
                ('db_host', models.CharField(blank=True, default='', help_text='Vide : le serveur par défaut. Permet de répartir les sociétés.', max_length=255, verbose_name='Serveur de base de données')),
                ('status', models.CharField(choices=[('PENDING_VERIFICATION', 'En attente de vérification'), ('PROVISIONING', 'Création en cours'), ('ACTIVE', 'Actif'), ('SUSPENDED', 'Suspendu'), ('PROVISION_FAILED', 'Échec de création'), ('SCHEDULED_DELETION', 'Suppression programmée'), ('DELETED', 'Supprimé')], db_index=True, default='PENDING_VERIFICATION', max_length=25, verbose_name='État')),
                ('provisioned_at', models.DateTimeField(blank=True, null=True, verbose_name='Créé le')),
                ('suspended_at', models.DateTimeField(blank=True, null=True, verbose_name='Suspendu le')),
                ('suspended_reason', models.TextField(blank=True, default='', verbose_name='Motif de suspension')),
                ('deletion_scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Suppression prévue le')),
                ('contact_email', models.EmailField(help_text="Adresse du responsable de l'abonnement. Distincte de l'e-mail public de la boutique, réglé dans les paramètres de l'espace.", max_length=254, verbose_name='E-mail du titulaire du compte')),
                ('contact_name', models.CharField(blank=True, default='', max_length=150, verbose_name='Nom du contact')),
                ('contact_phone', models.CharField(blank=True, default='', max_length=50, verbose_name='Téléphone du contact')),
                ('language', models.CharField(default='fr', help_text='Langue des messages envoyés par la plateforme.', max_length=5, verbose_name='Langue')),
                ('owner_user_id', models.IntegerField(blank=True, null=True, verbose_name='Identifiant du propriétaire')),
                ('owner_username', models.CharField(blank=True, default='', max_length=150, verbose_name='Identifiant de connexion du propriétaire')),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True, verbose_name="Fin de la période d'essai")),
            ],
            options={
                'verbose_name': 'Entreprise',
                'verbose_name_plural': 'Entreprises',
                'db_table': 'saas_company',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=253, unique=True, verbose_name="Nom d'hôte")),
                ('kind', models.CharField(choices=[('SUBDOMAIN', 'Sous-domaine de la plateforme'), ('CUSTOM', 'Domaine propre du client')], default='SUBDOMAIN', max_length=10, verbose_name='Type')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Principal')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Vérifié')),
                ('verification_token', models.CharField(blank=True, default='', max_length=64, verbose_name='Jeton de vérification DNS')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Vérifié le')),
                ('tls_status', models.CharField(choices=[('NONE', 'Sans certificat'), ('PENDING', "Certificat en cours d'obtention"), ('ISSUED', 'Certificat délivré'), ('FAILED', "Échec d'obtention")], default='NONE', max_length=10, verbose_name='État du certificat')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Nom d'hôte",
                'verbose_name_plural': "Noms d'hôte",
                'db_table': 'saas_domain',
                'ordering': ['-is_primary', 'hostname'],
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('delete_at', models.DateTimeField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, verbose_name="Adresse de l'employé")),
                ('firstname', models.CharField(blank=True, default='', max_length=150, verbose_name='Prénom')),
                ('lastname', models.CharField(blank=True, default='', max_length=150, verbose_name='Nom')),
                ('role', models.CharField(blank=True, default='', max_length=50, verbose_name='Rôle')),
                ('module_codes', models.JSONField(blank=True, default=list, verbose_name='Modules attribués')),
                ('token_hash', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('ACCEPTED', 'Acceptée'), ('EXPIRED', 'Expirée'), ('REVOKED', 'Révoquée')], default='PENDING', max_length=10, verbose_name='État')),
                ('expires_at', models.DateTimeField(verbose_name='Expire le')),
                ('invited_by_user_id', models.IntegerField(blank=True, null=True)),
                ('invited_by_label', models.CharField(blank=True, default='', max_length=150)),
                ('accepted_user_id', models.IntegerField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('send_count', models.PositiveIntegerField(default=0)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Invitation',
                'verbose_name_plural': 'Invitations',
                'db_table': 'saas_invitation',
                'ordering': ['-create_at'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=30, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('max_users', models.PositiveIntegerField(blank=True, help_text='Vide = illimité.', null=True, verbose_name="Nombre d'utilisateurs maximum")),
                ('max_products', models.PositiveIntegerField(blank=True, help_text='Vide = illimité.', null=True, verbose_name='Nombre de produits maximum')),
                ('price_xaf', models.PositiveIntegerField(default=0, verbose_name='Prix mensuel (FCFA)')),
                ('trial_days', models.PositiveIntegerField(default=0, verbose_name="Durée de l'essai (jours)")),
                ('is_active', models.BooleanField(default=True, verbose_name='Offre proposée')),
                ('is_default', models.BooleanField(default=False, help_text='Attribuée aux nouvelles inscriptions.', verbose_name='Offre par défaut')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Offre',
                'verbose_name_plural': 'Offres',
                'db_table': 'saas_plan',
                'ordering': ['order', 'price_xaf'],
            },
        ),
        migrations.CreateModel(
            name='SignupRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse à vérifier')),
                ('password_hash', models.CharField(blank=True, default='', max_length=128)),
                ('token_hash', models.CharField(db_index=True, max_length=64)),
                ('expires_at', models.DateTimeField(verbose_name='Expire le')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Vérifiée le')),
                ('login_ticket_hash', models.CharField(blank=True, default='', max_length=64)),
                ('login_ticket_expires_at', models.DateTimeField(blank=True, null=True)),
                ('login_ticket_used_at', models.DateTimeField(blank=True, null=True)),
                ('send_count', models.PositiveIntegerField(default=0)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=300)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signup', to='saas.company', verbose_name='Entreprise')),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
                'db_table': 'saas_signup_request',
                'ordering': ['-create_at'],
            },
        ),
        migrations.CreateModel(
            name='ProvisioningJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('PROVISION', "Création d'un espace"), ('MAIL', "Envoi d'un e-mail"), ('BACKUP', 'Sauvegarde'), ('EXPORT', 'Export client'), ('DELETE', "Suppression d'un espace"), ('USAGE_REFRESH', "Rafraîchissement de l'usage"), ('DOMAIN_VERIFY', "Vérification d'un nom d'hôte")], max_length=20, verbose_name='Nature')),
                ('status', models.CharField(choices=[('QUEUED', 'En attente'), ('RUNNING', 'En cours'), ('SUCCEEDED', 'Terminé'), ('FAILED', 'Échoué'), ('CANCELLED', 'Annulé')], default='QUEUED', max_length=12, verbose_name='État')),
                ('step', models.CharField(blank=True, default='', max_length=20, verbose_name='Étape atteinte')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Paramètres')),
                ('result', models.JSONField(blank=True, default=dict, verbose_name='Résultat')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='Tentatives')),
                ('max_attempts', models.PositiveIntegerField(default=3, verbose_name='Tentatives maximum')),
                ('last_error', models.TextField(blank=True, default='', verbose_name='Dernière erreur')),
                ('run_after', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='À exécuter après')),
                ('priority', models.SmallIntegerField(default=0, verbose_name='Priorité')),
                ('locked_by', models.CharField(blank=True, default='', max_length=100)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='saas.company', verbose_name='Entreprise')),
            ],
            options={
                'verbose_name': 'Travail',
                'verbose_name_plural': 'Travaux',
                'db_table': 'saas_provisioning_job',
                'ordering': ['-create_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_kind', models.CharField(choices=[('PLATFORM_STAFF', 'Équipe plateforme'), ('TENANT_OWNER', "Propriétaire de l'espace"), ('TENANT_USER', "Utilisateur de l'espace"), ('SYSTEM', 'Automatique')], default='SYSTEM', max_length=20, verbose_name="Type d'acteur")),
                ('actor_id', models.IntegerField(blank=True, null=True)),
                ('actor_label', models.CharField(blank=True, default='', help_text="Conservé en clair : l'acteur peut disparaître.", max_length=200, verbose_name='Acteur')),
                ('company_slug', models.CharField(blank=True, default='', help_text="Conservé en clair : survit à la suppression de l'espace.", max_length=40)),
                ('action', models.CharField(choices=[('SIGNUP_CREATED', 'Inscription créée'), ('EMAIL_VERIFIED', 'Adresse vérifiée'), ('PROVISION_QUEUED', 'Création mise en file'), ('PROVISION_STARTED', 'Création démarrée'), ('PROVISION_SUCCEEDED', 'Création réussie'), ('PROVISION_FAILED', 'Création échouée'), ('COMPANY_SUSPENDED', 'Espace suspendu'), ('COMPANY_REACTIVATED', 'Espace réactivé'), ('DELETION_SCHEDULED', 'Suppression programmée'), ('DELETION_CANCELLED', 'Suppression annulée'), ('COMPANY_DELETED', 'Espace supprimé'), ('INVITATION_SENT', 'Invitation envoyée'), ('INVITATION_ACCEPTED', 'Invitation acceptée'), ('INVITATION_REVOKED', 'Invitation révoquée'), ('DOMAIN_ADDED', "Nom d'hôte ajouté"), ('DOMAIN_VERIFIED', "Nom d'hôte vérifié"), ('DOMAIN_REMOVED', "Nom d'hôte retiré"), ('PLATFORM_LOGIN', 'Connexion à la plateforme'), ('PLATFORM_LOGIN_FAILED', 'Échec de connexion à la plateforme'), ('PLAN_CHANGED', "Changement d'offre"), ('MAIL_SENT', 'E-mail envoyé'), ('MAIL_FAILED', "Échec d'envoi d'e-mail")], db_index=True, max_length=60, verbose_name='Action')),
                ('target', models.CharField(blank=True, default='', max_length=200)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=300)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='saas.company', verbose_name='Entreprise')),
            ],
            options={
                'verbose_name': "Entrée du journal d'audit",
                'verbose_name_plural': "Journal d'audit",
                'db_table': 'saas_platform_audit_log',
                'ordering': ['-create_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='une_seule_offre_par_defaut'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='saas.company', verbose_name='Entreprise'),
        ),
        migrations.AddField(
            model_name='domain',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='saas.company', verbose_name='Entreprise'),
        ),
        migrations.AddField(
            model_name='company',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='saas.plan', verbose_name='Offre'),
        ),
        migrations.AddIndex(
            model_name='provisioningjob',
            index=models.Index(fields=['status', 'run_after', 'priority'], name='saas_job_a_traiter_idx'),
        ),
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('company', 'email'), name='une_invitation_en_cours_par_adresse'),
        ),
        migrations.AddConstraint(
            model_name='domain',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('company',), name='un_seul_domaine_principal_par_entreprise'),
        ),
    ]
