"""
Django settings for blanco project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import logging
import os
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ──── QR Code serveur ───────────────────────────────────────────────
from core.services.qrcode_service import QRCodeService
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

SECRET_KEY = config("SECRET_KEY")
DEBUG = config("DEBUG", cast=bool)
GET_IP_METHOD = config("GET_IP_METHOD", default=0, cast=int)

local_ip = QRCodeService.get_local_ip()

ALLOWED_HOSTS = config("ALLOWED_HOSTS", cast=lambda v: [s.strip() for s in v.split(',') if s.strip()])
if local_ip and local_ip not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(local_ip)  # Autoriser l'accès via l'IP locale détectée

logging.getLogger(__name__).debug("ALLOWED_HOSTS=%s", ALLOWED_HOSTS)
# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework.authtoken",
    "core",
]

# Custom User Model
AUTH_USER_MODEL = 'core.CustomUser'

# Refuse les comptes désactivés OU soft-supprimés (delete_at) à la connexion.
AUTHENTICATION_BACKENDS = [
    'core.auth_backends.ActiveStaffBackend',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "blanco.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, 'core/templates')],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.template.context_processors.i18n",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "core.context_processors.qrcode_context",
                "core.context_processors.system_settings_context",
                "core.context_processors.user_modules_context",
            ],
        },
    },
]

WSGI_APPLICATION = "blanco.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# Support both MySQL (production) and SQLite (development)
DATABASE_ENGINE = config("DATABASE_ENGINE", default="django.db.backends.sqlite3")

MYSQL_DATABASE = config("MYSQL_DATABASE")
MYSQL_USER = config("MYSQL_USER")
MYSQL_PASSWORD = config("MYSQL_PASSWORD")
MYSQL_HOST = config("MYSQL_HOST")
MYSQL_PORT = config("MYSQL_PORT")

if DATABASE_ENGINE == "django.db.backends.mysql":
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.mysql",
            "NAME": MYSQL_DATABASE,
            "USER": MYSQL_USER,
            "PASSWORD": MYSQL_PASSWORD,
            "HOST": MYSQL_HOST,
            "PORT": MYSQL_PORT,
        }
    }
else:
    # SQLite for development
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }




# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# ──── Sécurité transport / cookies ──────────────────────────────────
# L'application est servie en HTTP sur le LAN ; derrière un reverse proxy TLS,
# passer USE_HTTPS=True dans l'environnement pour activer les protections.
USE_HTTPS = config('USE_HTTPS', cast=bool, default=False)
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = 'same-origin'
X_FRAME_OPTIONS = 'DENY'
CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', cast=Csv(), default='')
if USE_HTTPS:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 60 * 60 * 24 * 30
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    # Le HEALTHCHECK Docker interroge l'API en HTTP local
    SECURE_REDIRECT_EXEMPT = [r'^api/test-connection/$']

# Limitation des tentatives de connexion (vue web /login/)
LOGIN_RATELIMIT_ATTEMPTS = config('LOGIN_RATELIMIT_ATTEMPTS', cast=int, default=5)
LOGIN_RATELIMIT_WINDOW_SECONDS = config('LOGIN_RATELIMIT_WINDOW_SECONDS', cast=int, default=15 * 60)


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

# Langue source du code (chaînes écrites en français) et langue par défaut
# lorsque ni cookie ni en-tête Accept-Language ne permettent de choisir.
LANGUAGE_CODE = "fr"

# Langues proposées par le sélecteur de l'en-tête (vue django.views.i18n.set_language).
# Les traductions vivent dans locale/<code>/LC_MESSAGES/{django,djangojs}.po ;
# voir `python manage.py translations --help` (extraction / compilation sans gettext).
LANGUAGES = [
    ("fr", "Français"),
    ("en", "English"),
]

LOCALE_PATHS = [os.path.join(BASE_DIR, "locale")]

# Le choix de langue est mémorisé dans un cookie (un an), pas en session,
# afin de survivre à la déconnexion.
LANGUAGE_COOKIE_NAME = "blanco_language"
LANGUAGE_COOKIE_AGE = 365 * 24 * 60 * 60
LANGUAGE_COOKIE_SAMESITE = "Lax"

TIME_ZONE = 'Africa/Douala'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'core/static'),
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Login URL
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'



# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Django REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'core.auth_backends.ActiveStaffTokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    # Throttles par portée (login, inscription) : voir core/api_views/auth_views.py
    'DEFAULT_THROTTLE_RATES': {
        'login': config('API_LOGIN_THROTTLE', default='10/min'),
        'signup': config('API_SIGNUP_THROTTLE', default='5/hour'),
    },
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.MultiPartParser',
        'rest_framework.parsers.FormParser',
    ],
}
